var forward = {
Default: {
	HPBoost: { },
	TPBoost: { },
	FirstAid: { },
	ListenToExp: { },
	Take: { },
	Chop: { },
	Mine: { }
},
Prince: {
	RoyalLineage: { },
	RoyalBell: { KingsVictorySong:5 },
	KingsVictorySong: { KingsMarch:5 },
	KingsMarch: { },
	Reinforce: { },
	ProofOfKingship: { Exchange:1, RenewLife:3, QuickOrder:5 },
	AttackCommand: { FireArms:1, FreezeArms:1, ShockArms:1, EmitWeapon:3, ResetWeapon:5 },
	DefenseCommand: { Reinforce:1, ResetWeapon:5, ImmunizationCommand:3, AmbitiousCommand:5 },
	FireArms: { },
	FreezeArms: { },
	ShockArms: { },
	EmitWeapon: { },
	ResetWeapon: { },
	ImmunizationCommand: { },
	AmbitiousCommand: { ProtectionCommand:5 },
	ProtectionCommand: { },
	Exchange: { },
	RenewLife: { },
	QuickOrder: { }
},
Gladiator: {
	BattlefieldRegular: { },
	SwordMastery: { WideEffect:5, Break:1, Rush:3, BindCut:3, Rampage:7, BladeRave:10 },
	HammerMastery: { WideEffect:5, CrushBlow:1, ArmBreaker:3, FreezingBlow:3, NineSmash:10 },
	StunAttack: { },
	WideEffect: { },
	Avenger: { Charge:3 },
	Break: { BindCut:5 },
	Rush: { BladeRave:5 },
	BindCut: { },
	Rampage: { },
	BladeRave: { },
	CrushBlow: { FreezingBlow:5 },
	ArmBreaker: { NineSmash:5 },
	FreezingBlow: { },
	NineSmash: { },
	BerserkersOath: { Avenger:1, Trance:5 },
	Trance: { StunAttack:3 },
	Charge: { },
	WolfHowl: { Charge:3 }
},
Hoplite: {
	Guardian: { },
	ShieldMastery: { LineGuard:1, FireGuard:5, FreezeGuard:5, ShockGuard:5, DivideGuard:3, OverGuard:8 },
	SpearMastery: { ChangeStep:1, Blitzritter:4, LongStride:7 },
	GuardHeal: { },
	Parry: { },
	MaterialParry: { },
	LineGuard: { },
	FireGuard: { },
	FreezeGuard: { },
	ShockGuard: { },
	DivideGuard: { },
	OverGuard: { },
	ChangeStep: { LongStride:3 },
	Blitzritter: { },
	LongStride: { },
	Revive: { GuardHeal:3 },
	EnGarde: { OverGuard:3 },
	Taunt: { Parry:5, MaterialParry:5 },
	CarefulWalk: { }
},
Buccaneer: {
	Trickster: { },
	RapierMastery: { SelfTaughtSwordplay:8, InTheDark:1, ChaseSaber:3, ChaseBlow:3, ChaseThrust:3, Hanging:5, MillionThrust:10 },
	GunMastery: { SelfTaughtSwordplay:8, QuickDraw:1, ChaseFlame:3, ChaseIce:3, ChaseThunder:3, RapidFire:5, MillionThrust:10 },
	SelfTaughtSwordplay: { },
	LadyLuck: { LimitBoost:3 },
	LimitBoost: { },
	InTheDark: { },
	ChaseSaber: { },
	ChaseBlow: { },
	ChaseThrust: { },
	Hanging: { },
	QuickDraw: { },
	ChaseFlame: { },
	ChaseIce: { },
	ChaseThunder: { },
	RapidFire: { },
	MillionThrust: { },
	EagleEye: { LimitBoost:3 },
	Troublemaking: { }
},
Ninja: {
	Smokescreen: { },
	DaggerMastery: { ShadowWeave:1, Meshizuna:3, HawkWings:5, PluralSlash:10 },
	Conceal: { NinpouSarutobi:1, NinpouCloudCover:5 },
	Acrobatics: { },
	Decapitation: { },
	FleshBullet: { PluralSlash:3 },
	ShadowWeave: { Meshizuna:3 },
	Meshizuna: { },
	HawkWings: { },
	PluralSlash: { },
	NinpouFukimibari: { NinpouWaterMirror:1, NinpouCaltrop:3 },
	NinpouWaterMirror: { Decapitation:3 },
	NinpouCaltrop: { Decapitation:5 },
	NinpouHeatHaze: { NinpouBeckoning:1, NinpouClone:3 },
	NinpouBeckoning: { FleshBullet:3 },
	NinpouClone: { FleshBullet:1 },
	NinpouSarutobi: { Acrobatics:3 },
	NinpouCloudCover: { Acrobatics:3 },
	EscapeArts: { }
},
Monk: {
	FocusEnergy: { },
	FistMastery: { ForceImpact:1, BurstFist:3, CounterI:8, CounterII:8, DarknessFist:10 },
	PilgrimsGain: { PilgrimsDeed:3 },
	ArtOfBloodReturn: { PilgrimsDeed:3 },
	PilgrimsDeed: { },
	ChakraZeal: { BurstFist:3 },
	Healing: { FullHealing:5, LineHeal:4, Refresh:2, BindRecovery:2 },
	FullHealing: { },
	LineHeal: { PartyHeal:5 },
	PartyHeal: { },
	Refresh: { Resurrect:2 },
	BindRecovery: { Resurrect:2 },
	Resurrect: { },
	ForceImpact: { },
	BurstFist: { DarknessFist:3 },
	CounterI: { },
	CounterII: { },
	DarknessFist: { },
	WalkingOverFire: { }
},
Zodiac: {
	EtherMastery: { },
	FlameMastery: { FlameAstrology:1, FlameConstellation:5 },
	IceMastery: { IceAstrology:1, IceConstellation:5 },
	ThunderMastery: { ThunderAstrology:1, ThunderConstellation:5 },
	SingularityTheorem: { ReturnEther:5 },
	ReturnEther: { Meteor:3 },
	FlameAstrology: { FlameForesight:5 },
	FlameConstellation: { FlameForesight:5 },
	FlameForesight: { },
	IceAstrology: { IceForesight:5 },
	IceConstellation: { IceForesight:5 },
	IceForesight: { },
	ThunderAstrology: { ThunderForesight:5 },
	ThunderConstellation: { ThunderForesight:5 },
	ThunderForesight: { },
	Meteor: { },
	EtherConcentration: { ReturnEther:5 },
	DarkEther: { SingularityTheorem:5, EtherConcentration:5 },
	PlanetObservation: { Meteor:5 }
},
Wildling: {
	BeastHeart: { },
	AnimalFriendship: { SacrificeI:3, SacrificeII:3, SummonSlime:10 },
	BeastKingMastery: { BeastReturn:1, SummonBird:1, SummonElephant:7, SummonHypnoOwl:5, SummonLionKing:10, SummonMole:1, SummonRagingBull:7, SummonSlime:6, SummonSnake:1, SummonTiger:10, SummonVenomfly:3 },
	BeastReturn: { },
	BeastRoar: { },
	BeastsOath: { },
	Drumming: { },
	SacrificeI: { SummonLionKing:5 },
	SacrificeII: { SummonTiger:5 },
	SummonBird: { },
	SummonElephant: { },
	SummonHypnoOwl: { SummonRagingBull:4 },
	SummonLionKing: { },
	SummonMole: { },
	SummonRagingBull: { },
	SummonSlime: { },
	SummonSnake: { },
	SummonTiger: { },
	SummonVenomfly: { SummonElephant:4 }
},
Arbalist: {
	GiantKill: { },
	CrossbowMastery: { HeavyShot:1, SnipeI:2, SnipeII:2, RandomShot:3, FireBarrage:5, FreezeBarrage:5, ThunderBarrage:5, HighSpeedAPBullet:7, Rainfall:10 },
	SurefireConcentration: { Extend:3 },
	NightVision: { },
	Extend: { },
	DoubleAction: { },
	HeavyShot: { RearMortarBombardment:5 },
	RearMortarBombardment: { DoubleAction:4 },
	SnipeI: { },
	SnipeII: { },
	RandomShot: { },
	FireBarrage: { },
	FreezeBarrage: { },
	ThunderBarrage: { },
	HighSpeedAPBullet: { DoubleAction:4 },
	Rainfall: { },
	IlluminatingShot: { NightVision:3 },
	SmokeBomb: { NightVision:3 },
	Ambush: { }
},
Farmer: {
	NaturesBlessing: { },
	Braveheart: { },
	BravingRain: { },
	CampMaster: { CPR:5, DismantleMastery:3 },
	CPR: { },
	CryToCeaseAttack: { SplitSpirit:5 },
	CursedEyeOfWeak: { MomentOfInjury:3 },
	DetectionMaster: { BravingRain:3, ReturnMaster:1, SafeWalking:5, TwoCropsAYear:5 },
	DismantleMastery: { },
	ForagingMastery: { WildSmell:3 },
	Loitering: { },
	Lullaby: { CryToCeaseAttack:1, CursedEyeOfWeak:3, MysterySeed:3 },
	MomentOfInjury: { Braveheart:5 },
	MysterySeed: { SplitSpirit:3 },
	ReturnMaster: { },
	SafeWalking: { },
	SplitSpirit: { },
	TwoCropsAYear: { },
	WildSmell: { }
},
Shogun: {
	DualWield: { },
	KatanaMastery: { HiltSmash:1, MorningStar:5, Catastrophe:5, OlympicSword:10 },
	Endure: { BloodstainedSpear:3, SuicideAssistant:1, SpiritualUnification:3, GreatMilitarist:5 },
	BloodstainedSpear: { Ikkitousen:3 },
	RestoreWill: { SuicideAssistant:1, VanguardsPrestige:3, RearGuardsHonor:3, SimultaneousFiring:5 },
	SuicideAssistant: { },
	HiltSmash: { },
	MorningStar: { },
	Catastrophe: { },
	OlympicSword: { },
	SpiritualUnification: { Ikkitousen:3 },
	GreatMilitarist: { OlympicSword:3 },
	VanguardsPrestige: { AssumeFormation:3 },
	RearGuardsHonor: { AssumeFormation:3 },
	AssumeFormation: { },
	Ikkitousen: { },
	SimultaneousFiring: { RagingDragonFormation:3 },
	RagingDragonFormation: { },
	RetreatToWin: { }
},
Yggdroid: {
	ReflectiveEnergy: { },
	DataAnalysis: { RedBot:1, BlueBot:1, YellowBot:1, Resupply:3, CoordinatedAttack:3 },
	DarkVision: { },
	AntibodyIncubation: { },
	Overheat: { ElectromagneticBarrier:3, HPCannon:10 },
	ElectromagneticBarrier: { },
	RedBot: { },
	BlueBot: { },
	YellowBot: { },
	Resupply: { Reflector:3, Shoot:5 },
	CoordinatedAttack: { Reflector:3, Shoot:5 },
	Reflector: { },
	Shoot: { },
	PartsRecovery: { Purge:3, RocketPunch:1, RocketHeadbutt:1, RocketJump:1 },
	Purge: { HPCannon:5 },
	RocketPunch: { },
	RocketHeadbutt: { },
	RocketJump: { },
	HPCannon: { }
}
};